
#Header Section

title: Portfolio
email: canajfisnik@gmail.com
description: Thinker // Problem solver // Positive person

background-image: bg-image.jpg
logo: logo.svg

#About Section -----------
my-face: face.jpg
my-face-hover: face-hover.jpg
my-face-more: my-face-more.jpg


personal-description: <p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit</strong>. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id CV <a href="assets/img/Fisnik Canaj_CV.pdf">click here</a>.</p>


#Menu Item List

menu:
- {name: Home, url: '#header'}
- {name: About Me, url: '#about'}
- {name: Works, url: '#work'}
- {name: Testimonial, url: '#clients'}
- {name: Contact, url: '#contact'}

# About section -----------

# Skills List

skills:
- {name: Communication, value: '7'}
- {name: Organization, value: '7'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '8'}
- {name: Planning, value: '7'}
- {name: Programming, value: '8'}
- {name: UX-Design, value: '6'}
- {name: Visual Design, value: '3'}

# Work section -----------

# Project
projects:
- {name: Occurrence Report, folder: proj-1, delay: '2000'}
- {name: ATS Occurrence Report, folder: proj-2, delay: '2400'}
- {name: ATS Engineering Occurrence Report, folder: proj-3, delay: '2800'}
- {name: Dangerous Goods Occurrence Report, folder: proj-4, delay: '3000'}
- {name: Birdstrike Occurrence Report, folder: proj-5, delay: '2000'}
- {name: Responsive template 1, folder: proj-6, delay: '2400'}
- {name: Responsive template 2, folder: proj-7, delay: '2800'}
- {name: Quote machine, folder: proj-8, delay: '3000'}


# Client section -----------

testimonial:
- {img: 'face-albert.jpg', name: 'Albert Lekal', title: 'Graphic designer', quotes: '<p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit,</strong> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>'}

- {img: 'face-aaroni2.jpg', name: 'Granit Gashi', title: 'Doctor', quotes: '<p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit,</strong> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua.</p>'}

- {img: 'face-atariboy.jpg', name: 'Atary Lekal', title: 'Manager', quotes: '<p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit,</strong> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>'}

- {img: 'face-teleject.jpg', name: 'Albert Lekal', title: 'Graphic designer', quotes: '<p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit,</strong> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>'}


logos:
- {logo: logo1.png}
- {logo: logo2.png}
- {logo: logo3.png}
- {logo: logo4.png}


# Contact section -----------



social-links:
- {name: 'github', title: 'github', link: 'https://github.com/fisnikcanaj1' }
- {name: 'linkedin', title: 'linkedin', link: 'https://www.linkedin.com/in/fisnik-canaj-687699b8' }
- {name: 'brand', title: 'freecodecamp', link: 'https://www.freecodecamp.org/fisnikcanaj1' }
- {name: 'facebook', title: 'facebook', link: 'https://www.facebook.com/fcanaj2' }
- {name: 'instagram', title: 'instagram', link: 'https://www.instagram.com/fisnikcanaj' }
