
#Header Section
title: Portfolio
email: canajfisnk@gmail.com
description: Thinker // Problem solver // Positive person

background-image: bg-image.jpg
logo: logo.svg

#About Section
my-face: face.jpg
my-face-hover: face-hover.jpg
my-face-more: my-face-more.jpg


personal-description: <p><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit</strong>. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


#Menu Item List

menu:
- {name: About Me, url: '#about'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

# Skills List

skills:
- {name: Communication, value: '7'}
- {name: Organization, value: '7'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '8'}
- {name: Planning, value: '7'}
- {name: Programming, value: '8'}
- {name: Visual Design, value: '3'}
- {name: UX-Design, value: '6'}

# Project
projects:
- {name: Project 1, folder: proj-1}
- {name: Project 2, folder: proj-2}
- {name: Project 3, folder: proj-3}
- {name: Project 4, folder: proj-4}
- {name: Project 5, folder: proj-5}
- {name: Project 6, folder: proj-6}
- {name: Project 7, folder: proj-7}
- {name: Project 8, folder: proj-8}
